### ISSUE TITLE
Flaky CoreTest.dnsEventLogTestAssert

### ISSUE THREAD

**Issue by Karm** [whalebone/sinkit-core#153]
The undermentioned test sometimes fails on Cirlce CI. Could you debug it, please? Is it a race condition? If you cannot reproduce it locally on your workstation, consider creating a resource limited VM (2 cores, 4G) and run it in the VM.

```
Tests run: 28, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 73.372 sec <<< FAILURE!
dnsEventLogTestAssert(biz.karms.sinkit.tests.core.CoreTest)  Time elapsed: 1.203 sec  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at biz.karms.sinkit.tests.core.CoreTest.dnsEventLogTestAssert(CoreTest.java:276)
```

**Comment by hugeox** [comment]
Same thing happens with ApiIntegrationTest.endToEndTest when the arbitrary waiting time isn't long enough.

**Comment by hugeox** [comment]
This is also connected with a comment in 
biz.karms.sinkit.tests.core.CoreTest#dnsEventLogTestPrepare:

> 

        dnsApiLoggingEJB.logDNSEvent(EventLogAction.BLOCK,
                "10.1.1.1",
                "10.1.1.2",
                "requestFqdn",
                "requestType",
                "seznam.cz",
                "10.1.1.3",
                ids,
                null, //TODO
                LOGGER);
        // The async task follows Fire and Forget. TODO: dnsEventLogTestAssert must wait
