### ISSUE TITLE
SEVERE Exceptions logged on long DNS API calls

### ISSUE THREAD

**Issue by robcza** [whalebone/sinkit-core#64]
SEVERE exceptions are raised on misformatted fqdn API requests from the resolver. This should be handled just with logging such event on Debug log level only.

```
instance | 2015-11-17T08:44:16.302136500Z 08:44:16,301 SEVERE [biz.karms.sinkit.ejb.impl.DNSApiEJB] (default task-128) customListsLookup: <nonsense.fqdn> in not a valid IP address nor a valid FQDN.
instance | 2015-11-17T08:44:18.644422700Z 08:44:18,644 WARNING [biz.karms.sinkit.ejb.impl.DNSApiEJB] (default task-78) getSinkHole: Feed mode decision:
instance | 2015-11-17T08:44:18.644580200Z 08:44:18,644 WARNING [biz.karms.sinkit.ejb.impl.DNSApiEJB] (default task-78) getSinkHole: Log.
instance | 2015-11-17T08:44:20.879714600Z 08:44:20,879 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-82) RESTEASY002010: Failed to execute: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://feedcore-lb:8080/sinkit/rest/blacklist/dns/1.2.3.4/
instance | 2015-11-17T08:44:20.879795500Z 	at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:114)
instance | 2015-11-17T08:44:20.879808300Z 	at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43)
instance | 2015-11-17T08:44:20.880588400Z 	at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:48)
instance | 2015-11-17T08:44:20.880645600Z 	at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:445)
instance | 2015-11-17T08:44:20.880660000Z 	at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:254)
instance | 2015-11-17T08:44:20.880671200Z 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:191)
instance | 2015-11-17T08:44:20.880684000Z 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
instance | 2015-11-17T08:44:20.880694700Z 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
instance | 2015-11-17T08:44:20.880705100Z 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
instance | 2015-11-17T08:44:20.880715400Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
instance | 2015-11-17T08:44:20.880725400Z 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
instance | 2015-11-17T08:44:20.880741600Z 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
instance | 2015-11-17T08:44:20.880753000Z 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
instance | 2015-11-17T08:44:20.880763800Z 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
instance | 2015-11-17T08:44:20.880774000Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
instance | 2015-11-17T08:44:20.880784200Z 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
instance | 2015-11-17T08:44:20.880794600Z 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
instance | 2015-11-17T08:44:20.880804900Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
instance | 2015-11-17T08:44:20.880815000Z 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
instance | 2015-11-17T08:44:20.880832200Z 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
instance | 2015-11-17T08:44:20.880843900Z 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
instance | 2015-11-17T08:44:20.880859200Z 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
instance | 2015-11-17T08:44:20.880882900Z 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
instance | 2015-11-17T08:44:20.880894300Z 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
instance | 2015-11-17T08:44:20.880905000Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
instance | 2015-11-17T08:44:20.880915200Z 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
instance | 2015-11-17T08:44:20.880925300Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
instance | 2015-11-17T08:44:20.880935500Z 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
instance | 2015-11-17T08:44:20.880946000Z 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
instance | 2015-11-17T08:44:20.880956800Z 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
instance | 2015-11-17T08:44:20.880967300Z 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
instance | 2015-11-17T08:44:20.880977700Z 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
instance | 2015-11-17T08:44:20.880988200Z 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198)
instance | 2015-11-17T08:44:20.880998300Z 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788)
instance | 2015-11-17T08:44:20.881008600Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
instance | 2015-11-17T08:44:20.881019300Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
instance | 2015-11-17T08:44:20.881030100Z 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Karm** [comment]
Empty Answer element?

**Comment by Karm** [comment]
There are 3 different, completely unrelated things going on here:
 1. ```task-128) customListsLookup: <nonsense.fqdn> in not a valid IP address nor a valid FQDN.```, an invalid query had been presented by GoDNS and it was rejected. No rules lookup, no feeds lookup, no sinkholing nor logging. The immediate response to the client in this case is: It is O.K., don't sinkhole. _Call to action:_ Change log level to FINE.
 1. ```task-78) getSinkHole: Feed mode decision:
task-78) getSinkHole: Log.``` An ordinary operation, some FQDN or IP, completely unrelated to the one being processed in the thread ```task-128``` was logged. _Call to action:_ Change log level to FINE.
 1. ```RESTEASY003210: Could not find resource for full path: http://feedcore-lb:8080/sinkit/rest/blacklist/dns/1.2.3.4/``` GoDNS requested ```http://feedcore-lb:8080/sinkit/rest/blacklist/dns/1.2.3.4/```, where ```1.2.3.4/``` is the DNS client IP address. The actual path parameter with FQDN or IP to be checked for blacklisting is *missing*. It should have been: ```http://feedcore-lb:8080/sinkit/rest/blacklist/dns/1.2.3.4/malicious.domain.example```.  _Call to action:_ Modify GoDNS so as it doesn't ask empty queries.

**Comment by Karm** [comment]
Done.
